all: 
	(cd robots; make)
	(cd multibuffer; make)
	(cd gritter; make)
	(cd mergesort_parallel; make)

clean:
	(cd robots; make clean)
	(cd multibuffer; make clean)
	(cd gritter; make clean)
	(cd mergesort_parallel; make clean)
