all: 
	(cd robots; make)
	(cd multibuffer; make)
	(cd gritter; make)
	(cd mergesort; make)
	(cd robofab; make)
	make -C enclavamiento

clean:
	(cd robots; make clean)
	(cd multibuffer; make clean)
	(cd gritter; make clean)
	(cd mergesort; make)
	(cd robofab; make clean)
	(cd enclavamiento; make clean)
